// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cardio - AI | Seu Coração em Boas Mãos",
  description: "Monitore sua saúde cardiovascular com inteligência artificial. O Cardio - AI usa tecnologia de ponta para analisar seus batimentos cardíacos e fornecer insights personalizados.",
  keywords: ["cardio", "saúde", "coração", "inteligência artificial", "monitoramento cardíaco", "batimentos", "AI"],
  authors: [{ name: "Cardio - AI Team" }],
  openGraph: {
    title: "Cardio - AI | Seu Coração em Boas Mãos",
    description: "Monitore sua saúde cardiovascular com inteligência artificial",
    type: "website",
    url: "https://cardi-ai-nine.vercel.app/",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
